# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  jshint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install gulp, jshint requirements
          command: npm install --save-dev gulp jshint gulp-jshint jshint-stylish gulp-concat node-sass gulp-jsvalidate
      - run:
          name: Install gulp command line
          command: sudo npm install --global gulp-cli
      - run:
          name: Run gulp jshint
          command: gulp jshint --gulpfile ./js/gulpfile.js

  style:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install gulp, sass requirements
          command: npm install --save-dev gulp gulp-sass gulp-concat node-sass gulp-jsvalidate
      - run:
          name: Install gulp command line
          command: sudo npm install --global gulp-cli
      - run:
          name: Run gulp style
          command: gulp styles --gulpfile ./js/gulpfile.js

  validate:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install gulp, jsValidate requirements
          command: npm install --save-dev gulp gulp-jsvalidate
      - run:
          name: Install gulp command line
          command: sudo npm install --global gulp-cli
      - run:
          name: Run gulp validate
          command: gulp jsValidate --gulpfile ./js/gulpfile.js

workflows:
  version: 2
  jshint_style:
    jobs:
      - jshint
      - validate
      - style