# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install --save-dev gulp jshint gulp-jshint jshint-stylish gulp-sass gulp-concat node-sass
      - run: sudo npm install --global gulp-cli
      - run: gulp jshint --gulpfile ./js/gulpfile.js
      - run: gulp styles --gulpfile ./js/gulpfile.js
